"""Constrain Goal.prepId, and correct the premise migration 043 rested on.

Migration `043` added `Goal.prepId` as a plain `String` with an index and no foreign key, and said so
deliberately: "matching `courseId`, `topicId` and `spaceId` on this same table", on the reasoning that
one column constrained differently from its three siblings is a worse inconsistency than a dangling
id. It recorded the looseness as an open item covering all four columns together.

**The premise was wrong, and it was wrong because it was read from the ORM rather than the database.**
`Goal` in `progress/db_models.py` declares those three as bare `String`, but the live table has
carried foreign keys on all three since the Prisma schema: `Goal_courseId_fkey`, `Goal_topicId_fkey`
and `Goal_circleId_fkey` — the last still under its pre-rename name — each `ON DELETE SET NULL`,
`ON UPDATE CASCADE`. So `prepId` was not matching its siblings; it was the only unconstrained link on
the row, and "consistency within the row" argued for the opposite of what was done.

This adds the one missing constraint. The three existing ones need no DDL and are now declared in the
model, which is the other half of the correction: a model that understates the schema is how an
autogenerated migration ends up proposing to add a constraint that is already there.

`ON DELETE SET NULL`, matching the siblings exactly. A goal outlives the thing it was attached to —
deleting a preparation should detach the goal, not delete the learner's stated intention with it, which
is what `CASCADE` would do. `userId` remains the only cascading link on this table, correctly: a goal
belonging to no one is not a goal.

**Safe on this data.** `prepId` is set on zero of six rows, so there is nothing to orphan and the
constraint validates immediately. Checked before writing this rather than assumed, because
`ADD CONSTRAINT` on a column with dangling ids fails the whole migration.

Revision ID: 044_add_goal_prep_fk
Revises: 043_add_goal_prep_link
Create Date: 2026-08-22
"""

from alembic import op

revision = "044_add_goal_prep_fk"
down_revision = "043_add_goal_prep_link"
branch_labels = None
depends_on = None

CONSTRAINT = "Goal_prepId_fkey"


def upgrade() -> None:
    op.create_foreign_key(
        CONSTRAINT,
        source_table="Goal",
        referent_table="ExamPrep",
        local_cols=["prepId"],
        remote_cols=["id"],
        ondelete="SET NULL",
    )


def downgrade() -> None:
    op.drop_constraint(CONSTRAINT, "Goal", type_="foreignkey")
