"""
Action Service.
Executes structured actions triggered by the AI (e.g., creating courses).
"""

import json

from prisma import Prisma
from prisma.models import User

db = Prisma()


class ActionService:
    async def execute_action(self, action_type: str, action_data: dict, user_id: str):
        """
        Route the action to the correct handler.
        """
        print(f"⚡ EXECUTING ACTION: {action_type} for User {user_id}")

        if not db.is_connected():
            await db.connect()

        if action_type == "create_course":
            return await self.create_course(action_data, user_id)

        # Add more actions here later (create_goal, create_schedule, etc.)
        return {"status": "error", "message": f"Unknown action: {action_type}"}

    async def create_course(self, data: dict, user_id: str):
        """
        Creates a course with modules and topics in the DB.
        Expected data: { "title": "...", "modules": [ { "title": "...", "topics": [...] } ] }
        """
        try:
            # 1. Create the Course
            course = await db.course.create(
                data={
                    "userId": user_id,
                    "title": data.get("title", "AI Generated Course"),
                    "description": data.get("description", "Generated by Maigie AI"),
                    "difficulty": data.get("difficulty", "BEGINNER"),
                    "isAIGenerated": True,
                }
            )

            # 2. Create Modules and Topics (Nested loop)
            modules_data = data.get("modules", [])
            for i, mod_data in enumerate(modules_data):
                module = await db.module.create(
                    data={
                        "courseId": course.id,
                        "title": mod_data.get("title", f"Module {i+1}"),
                        "order": float(i),
                    }
                )

                # Create Topics for this Module
                topics_data = mod_data.get("topics", [])
                for j, top_data in enumerate(topics_data):
                    await db.topic.create(
                        data={
                            "moduleId": module.id,
                            "title": (
                                top_data
                                if isinstance(top_data, str)
                                else top_data.get("title")
                            ),
                            "order": float(j),
                        }
                    )

            return {
                "status": "success",
                "action": "create_course",
                "course_id": course.id,
                "message": f"Successfully created course: {course.title}",
            }

        except Exception as e:
            print(f" Action Failed: {e}")
            return {"status": "error", "message": str(e)}


# Global Instance
action_service = ActionService()